//
//  Database.swift
//  Skyrise Bureau
//
//  Created by Milind Contractor on 5/11/25.
//

import Foundation

// MARK: Aircraft Database
class AircraftDatabase {
    static let shared = AircraftDatabase()
    
    let allAircraft: [Aircraft]
    
    private init() {
        allAircraft = [
            // EXTRAS
            Aircraft(
                modelCode: "TU144",
                name: "Tupolev Tu-144",
                manufacturer: .tupolev,
                category: .extras,
                description: "The Soviet Union's supersonic rival to the Concorde. Despite its troubled service history, the Tu-144 represents an ambitious era of aviation innovation.",
                maxRange: 6500,
                cruiseSpeed: 2150,
                maxSeats: 140,
                fuelCapacity: 70000,
                fuelBurnRate: 15.5,
                minRunwayLength: 3200,
                defaultSeating: SeatingConfig(economy: 90, premiumEconomy: 0, business: 20, first: 0),
                purchasePrice: 120_000_000,
                maintenanceCostPerHour: 25000,
                yearIntroduced: 1968,
                isEndgame: false,
                isSupersonic: true,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "CONCORDE",
                name: "BAC-Aérospatiale Concorde",
                manufacturer: .airbus,
                category: .extras,
                description: "The iconic supersonic airliner that redefined luxury air travel. Capable of crossing the Atlantic in under 3.5 hours at twice the speed of sound.",
                maxRange: 7250,
                cruiseSpeed: 2180,
                maxSeats: 128,
                fuelCapacity: 95680,
                fuelBurnRate: 17.2,
                minRunwayLength: 3400,
                defaultSeating: SeatingConfig(economy: 0, premiumEconomy: 0, business: 64, first: 0),
                purchasePrice: 150_000_000,
                maintenanceCostPerHour: 30000,
                yearIntroduced: 1976,
                isEndgame: false,
                isSupersonic: true,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 6
            ),
            Aircraft(
                modelCode: "DHC6",
                name: "De Havilland Canada DHC-6 'Twin Otter'",
                manufacturer: .dehavilland,
                category: .extras,
                description: "A rugged STOL aircraft perfect for remote operations. Known for its exceptional short-field performance and reliability in harsh conditions.",
                maxRange: 1300,
                cruiseSpeed: 340,
                maxSeats: 19,
                fuelCapacity: 1137,
                fuelBurnRate: 0.35,
                minRunwayLength: 335,
                defaultSeating: SeatingConfig(economy: 19, premiumEconomy: 0, business: 0, first: 0),
                purchasePrice: 6_500_000,
                maintenanceCostPerHour: 450,
                yearIntroduced: 1965,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 0
            ),
            
            // COMMUTER
            Aircraft(
                modelCode: "ATR42",
                name: "ATR 42",
                manufacturer: .atr,
                category: .commuter,
                description: "A fuel-efficient turboprop ideal for regional routes. Popular with airlines for its low operating costs and reliable performance.",
                maxRange: 1528,
                cruiseSpeed: 510,
                maxSeats: 50,
                fuelCapacity: 4500,
                fuelBurnRate: 0.65,
                minRunwayLength: 1165,
                defaultSeating: SeatingConfig(economy: 50, premiumEconomy: 0, business: 0, first: 0),
                purchasePrice: 18_000_000,
                maintenanceCostPerHour: 850,
                yearIntroduced: 1985,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 1
            ),
            Aircraft(
                modelCode: "ATR72",
                name: "ATR 72",
                manufacturer: .atr,
                category: .commuter,
                description: "The stretched version of the ATR 42, offering more capacity while maintaining excellent fuel efficiency for short-haul operations.",
                maxRange: 1528,
                cruiseSpeed: 510,
                maxSeats: 78,
                fuelCapacity: 5000,
                fuelBurnRate: 0.75,
                minRunwayLength: 1333,
                defaultSeating: SeatingConfig(economy: 72, premiumEconomy: 4, business: 0, first: 0),
                purchasePrice: 26_000_000,
                maintenanceCostPerHour: 1100,
                yearIntroduced: 1989,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "DHC8",
                name: "De Havilland Canada DHC-8 Dash 8 (Q400)",
                manufacturer: .dehavilland,
                category: .commuter,
                description: "A versatile turboprop with advanced noise reduction. The Q400 variant offers near-jet speeds with turboprop economics.",
                maxRange: 2040,
                cruiseSpeed: 667,
                maxSeats: 90,
                fuelCapacity: 6526,
                fuelBurnRate: 0.85,
                minRunwayLength: 1425,
                defaultSeating: SeatingConfig(economy: 78, premiumEconomy: 8, business: 0, first: 0),
                purchasePrice: 32_000_000,
                maintenanceCostPerHour: 1350,
                yearIntroduced: 1984,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 2
            ),
            
            // REGIONAL JETS
            Aircraft(
                modelCode: "ERJ145",
                name: "ERJ 145",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "A pioneering 50-seat regional jet that revolutionized short-haul travel. Compact and efficient for thin routes.",
                maxRange: 3334,
                cruiseSpeed: 833,
                maxSeats: 50,
                fuelCapacity: 5737,
                fuelBurnRate: 1.1,
                minRunwayLength: 1753,
                defaultSeating: SeatingConfig(economy: 46, premiumEconomy: 0, business: 2, first: 0),
                purchasePrice: 30_000_000,
                maintenanceCostPerHour: 1450,
                yearIntroduced: 1996,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "ERJ170",
                name: "ERJ 170",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "Part of Embraer's E-Jet family, offering mainline comfort in a regional package. Popular for its passenger appeal and economics.",
                maxRange: 3889,
                cruiseSpeed: 870,
                maxSeats: 80,
                fuelCapacity: 9980,
                fuelBurnRate: 1.45,
                minRunwayLength: 1644,
                defaultSeating: SeatingConfig(economy: 66, premiumEconomy: 6, business: 3, first: 0),
                purchasePrice: 45_000_000,
                maintenanceCostPerHour: 1850,
                yearIntroduced: 2004,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "ERJ190",
                name: "ERJ 190",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The largest of the first-generation E-Jets, bridging the gap between regional and narrow-body aircraft with excellent range.",
                maxRange: 4537,
                cruiseSpeed: 870,
                maxSeats: 114,
                fuelCapacity: 13365,
                fuelBurnRate: 1.75,
                minRunwayLength: 1778,
                defaultSeating: SeatingConfig(economy: 88, premiumEconomy: 12, business: 4, first: 0),
                purchasePrice: 52_000_000,
                maintenanceCostPerHour: 2100,
                yearIntroduced: 2005,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "E175E2",
                name: "ERJ 175-E2",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The second-generation E-Jet with improved fuel efficiency and lower emissions. Features advanced aerodynamics and modern engines.",
                maxRange: 3704,
                cruiseSpeed: 871,
                maxSeats: 90,
                fuelCapacity: 11340,
                fuelBurnRate: 1.35,
                minRunwayLength: 1644,
                defaultSeating: SeatingConfig(economy: 70, premiumEconomy: 8, business: 4, first: 0),
                purchasePrice: 56_000_000,
                maintenanceCostPerHour: 1950,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "E190E2",
                name: "ERJ 190-E2",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The enhanced E190 with new-generation engines and winglets. Offers 17% lower fuel consumption than its predecessor.",
                maxRange: 5278,
                cruiseSpeed: 871,
                maxSeats: 114,
                fuelCapacity: 13620,
                fuelBurnRate: 1.65,
                minRunwayLength: 1704,
                defaultSeating: SeatingConfig(economy: 88, premiumEconomy: 12, business: 4, first: 0),
                purchasePrice: 62_000_000,
                maintenanceCostPerHour: 2050,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 115,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "A220-300",
                name: "Airbus A220-300",
                manufacturer: .airbus,
                category: .regionalJet,
                description: "Originally the Bombardier CSeries, this cutting-edge aircraft offers mainline comfort with regional jet efficiency and exceptional range.",
                maxRange: 6297,
                cruiseSpeed: 870,
                maxSeats: 160,
                fuelCapacity: 21945,
                fuelBurnRate: 2.15,
                minRunwayLength: 1463,
                defaultSeating: SeatingConfig(economy: 120, premiumEconomy: 18, business: 8, first: 0),
                purchasePrice: 91_000_000,
                maintenanceCostPerHour: 2650,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "SSJ100",
                name: "Sukhoi Superjet 100",
                manufacturer: .sukhoi,
                category: .regionalJet,
                description: "Russia's modern regional jet featuring Western avionics. Designed for efficiency on short to medium-haul routes.",
                maxRange: 4578,
                cruiseSpeed: 828,
                maxSeats: 108,
                fuelCapacity: 13790,
                fuelBurnRate: 1.8,
                minRunwayLength: 1780,
                defaultSeating: SeatingConfig(economy: 84, premiumEconomy: 10, business: 4, first: 0),
                purchasePrice: 36_000_000,
                maintenanceCostPerHour: 1750,
                yearIntroduced: 2011,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 3
            ),
            
            // NARROW BODY
            Aircraft(
                modelCode: "A318",
                name: "Airbus A318",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The smallest member of the A320 family, nicknamed 'Baby Bus'. Perfect for thin routes and hot-and-high operations.",
                maxRange: 5950,
                cruiseSpeed: 829,
                maxSeats: 136,
                fuelCapacity: 24210,
                fuelBurnRate: 2.4,
                minRunwayLength: 1780,
                defaultSeating: SeatingConfig(economy: 102, premiumEconomy: 12, business: 6, first: 0),
                purchasePrice: 75_000_000,
                maintenanceCostPerHour: 2800,
                yearIntroduced: 2003,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "A319",
                name: "Airbus A319",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "A versatile narrow-body with excellent range for its size. Popular with both mainline and low-cost carriers worldwide.",
                maxRange: 6850,
                cruiseSpeed: 829,
                maxSeats: 156,
                fuelCapacity: 23859,
                fuelBurnRate: 2.55,
                minRunwayLength: 2090,
                defaultSeating: SeatingConfig(economy: 114, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 92_000_000,
                maintenanceCostPerHour: 3100,
                yearIntroduced: 1996,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 115,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A320",
                name: "Airbus A320",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The world's best-selling single-aisle airliner. Revolutionary fly-by-wire technology and exceptional reliability made it an industry standard.",
                maxRange: 6150,
                cruiseSpeed: 829,
                maxSeats: 180,
                fuelCapacity: 27200,
                fuelBurnRate: 2.75,
                minRunwayLength: 2090,
                defaultSeating: SeatingConfig(economy: 132, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 101_000_000,
                maintenanceCostPerHour: 3300,
                yearIntroduced: 1988,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A321",
                name: "Airbus A321",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The largest A320 family member, offering maximum capacity and flexibility. The stretched fuselage maximizes efficiency on high-density routes.",
                maxRange: 5950,
                cruiseSpeed: 829,
                maxSeats: 220,
                fuelCapacity: 32840,
                fuelBurnRate: 3.1,
                minRunwayLength: 2180,
                defaultSeating: SeatingConfig(economy: 156, premiumEconomy: 24, business: 12, first: 0),
                purchasePrice: 118_000_000,
                maintenanceCostPerHour: 3600,
                yearIntroduced: 1994,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "A319neo",
                name: "Airbus A319neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The new engine option A319 with improved fuel efficiency and reduced emissions. Features sharklet wingtips and modern engines.",
                maxRange: 6850,
                cruiseSpeed: 833,
                maxSeats: 160,
                fuelCapacity: 26730,
                fuelBurnRate: 2.35,
                minRunwayLength: 2000,
                defaultSeating: SeatingConfig(economy: 116, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 102_000_000,
                maintenanceCostPerHour: 2950,
                yearIntroduced: 2019,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A320neo",
                name: "Airbus A320neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The next generation A320 with 15% better fuel efficiency. New engines and aerodynamic improvements maintain Airbus's narrow-body dominance.",
                maxRange: 6300,
                cruiseSpeed: 833,
                maxSeats: 194,
                fuelCapacity: 26730,
                fuelBurnRate: 2.5,
                minRunwayLength: 2000,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 20, business: 12, first: 0),
                purchasePrice: 110_500_000,
                maintenanceCostPerHour: 3050,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A321neo",
                name: "Airbus A321neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The most capable single-aisle aircraft available. Exceptional range enables transatlantic routes while maintaining excellent economics.",
                maxRange: 7400,
                cruiseSpeed: 833,
                maxSeats: 244,
                fuelCapacity: 32840,
                fuelBurnRate: 2.85,
                minRunwayLength: 2180,
                defaultSeating: SeatingConfig(economy: 168, premiumEconomy: 28, business: 16, first: 0),
                purchasePrice: 129_500_000,
                maintenanceCostPerHour: 3400,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "DC9-31",
                name: "DC-9-31",
                manufacturer: .mcdonnellDouglas,
                category: .narrowBody,
                description: "A classic short-haul jet from aviation's golden age. The DC-9's simplicity and reliability made it a workhorse for decades.",
                maxRange: 2150,
                cruiseSpeed: 810,
                maxSeats: 115,
                fuelCapacity: 13636,
                fuelBurnRate: 2.8,
                minRunwayLength: 1920,
                defaultSeating: SeatingConfig(economy: 99, premiumEconomy: 6, business: 4, first: 0),
                purchasePrice: 45_000_000,
                maintenanceCostPerHour: 2400,
                yearIntroduced: 1967,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "MD82",
                name: "MD-82",
                manufacturer: .mcdonnellDouglas,
                category: .narrowBody,
                description: "Part of the MD-80 'Super 80' series, a stretched DC-9 variant. Known for its distinctive rear-mounted engines and long service life.",
                maxRange: 3540,
                cruiseSpeed: 811,
                maxSeats: 172,
                fuelCapacity: 21114,
                fuelBurnRate: 3.25,
                minRunwayLength: 2438,
                defaultSeating: SeatingConfig(economy: 132, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 62_000_000,
                maintenanceCostPerHour: 3000,
                yearIntroduced: 1981,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B707-320C",
                name: "Boeing 707-320C",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The aircraft that ushered in the jet age. The 707 revolutionized long-haul travel and established Boeing as a commercial aviation leader.",
                maxRange: 9400,
                cruiseSpeed: 885,
                maxSeats: 189,
                fuelCapacity: 90770,
                fuelBurnRate: 5.2,
                minRunwayLength: 3048,
                defaultSeating: SeatingConfig(economy: 126, premiumEconomy: 24, business: 12, first: 2),
                purchasePrice: 55_000_000,
                maintenanceCostPerHour: 4200,
                yearIntroduced: 1958,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B717-200",
                name: "Boeing 717-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "Originally the MD-95, this efficient 100-seater excels on short-haul routes. Known for low noise and excellent hot-day performance.",
                maxRange: 3815,
                cruiseSpeed: 811,
                maxSeats: 134,
                fuelCapacity: 17560,
                fuelBurnRate: 2.5,
                minRunwayLength: 1860,
                defaultSeating: SeatingConfig(economy: 104, premiumEconomy: 12, business: 6, first: 0),
                purchasePrice: 48_000_000,
                maintenanceCostPerHour: 2300,
                yearIntroduced: 1999,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B727-200",
                name: "Boeing 727-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "A tri-jet legend with exceptional short-field performance. The 727's versatility made it one of aviation's most successful airliners.",
                maxRange: 4630,
                cruiseSpeed: 917,
                maxSeats: 189,
                fuelCapacity: 31755,
                fuelBurnRate: 4.0,
                minRunwayLength: 2438,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 58_000_000,
                maintenanceCostPerHour: 3500,
                yearIntroduced: 1967,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B737-200ADV",
                name: "Boeing 737-200 Advance",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The improved second generation 737 with more powerful engines. A rugged workhorse that served in the harshest conditions worldwide.",
                maxRange: 3700,
                cruiseSpeed: 815,
                maxSeats: 136,
                fuelCapacity: 19640,
                fuelBurnRate: 2.9,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 108, premiumEconomy: 10, business: 6, first: 0),
                purchasePrice: 42_000_000,
                maintenanceCostPerHour: 2500,
                yearIntroduced: 1971,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B737-300",
                name: "Boeing 737-300",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The first 737 Classic variant, featuring modern turbofan engines. Launched the 737 into the jet age and saved Boeing's narrow-body program.",
                maxRange: 4400,
                cruiseSpeed: 794,
                maxSeats: 149,
                fuelCapacity: 23814,
                fuelBurnRate: 2.95,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 114, premiumEconomy: 12, business: 8, first: 0),
                purchasePrice: 68_000_000,
                maintenanceCostPerHour: 2850,
                yearIntroduced: 1984,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B737-800NG",
                name: "Boeing 737-800 NG",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The most popular 737 variant ever built. Exceptional reliability and economics made it the backbone of countless airline fleets.",
                maxRange: 5436,
                cruiseSpeed: 842,
                maxSeats: 189,
                fuelCapacity: 26020,
                fuelBurnRate: 2.7,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 102_000_000,
                maintenanceCostPerHour: 3150,
                yearIntroduced: 1998,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B737MAX8",
                name: "Boeing 737 MAX 8",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The latest generation 737 with 14% better fuel efficiency. Advanced winglets and engines provide excellent performance and range.",
                maxRange: 6570,
                cruiseSpeed: 839,
                maxSeats: 210,
                fuelCapacity: 25816,
                fuelBurnRate: 2.45,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 121_600_000,
                maintenanceCostPerHour: 3050,
                yearIntroduced: 2017,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "B737MAX9",
                name: "Boeing 737 MAX 9",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The stretched MAX variant offering increased capacity. Maintains the MAX family's efficiency while serving high-density markets.",
                maxRange: 6570,
                cruiseSpeed: 839,
                maxSeats: 220,
                fuelCapacity: 25816,
                fuelBurnRate: 2.55,
                minRunwayLength: 2550,
                defaultSeating: SeatingConfig(economy: 156, premiumEconomy: 24, business: 14, first: 0),
                purchasePrice: 128_900_000,
                maintenanceCostPerHour: 3200,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "B757-200",
                name: "Boeing 757-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "A powerful narrow-body with exceptional hot-and-high performance. The 757's range and capability made it irreplaceable on many routes.",
                maxRange: 7222,
                cruiseSpeed: 850,
                maxSeats: 239,
                fuelCapacity: 43490,
                fuelBurnRate: 3.4,
                minRunwayLength: 2072,
                defaultSeating: SeatingConfig(economy: 162, premiumEconomy: 30, business: 16, first: 0),
                purchasePrice: 125_000_000,
                maintenanceCostPerHour: 3800,
                yearIntroduced: 1983,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "TU204SM",
                name: "Tupolev Tu-204SM",
                manufacturer: .tupolev,
                category: .narrowBody,
                description: "A modernized Russian narrow-body with Western engines and avionics. Designed to compete with Boeing and Airbus offerings.",
                maxRange: 4300,
                cruiseSpeed: 850,
                maxSeats: 210,
                fuelCapacity: 36000,
                fuelBurnRate: 3.25,
                minRunwayLength: 2300,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 72_000_000,
                maintenanceCostPerHour: 3100,
                yearIntroduced: 2010,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "MC21-300",
                name: "Irkut MC-21-300",
                manufacturer: .irkut,
                category: .narrowBody,
                description: "Russia's most advanced narrow-body jet featuring composite wings. Designed for efficiency and passenger comfort with a spacious cabin.",
                maxRange: 6000,
                cruiseSpeed: 870,
                maxSeats: 211,
                fuelCapacity: 23790,
                fuelBurnRate: 2.6,
                minRunwayLength: 2100,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 92_000_000,
                maintenanceCostPerHour: 3000,
                yearIntroduced: 2017,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            
            // WIDE BODY
            Aircraft(
                modelCode: "A330-300",
                name: "Airbus A330-300",
                manufacturer: .airbus,
                category: .wideBody,
                description: "A versatile twin-engine wide-body perfect for long-haul routes. Excellent economics and reliability made it a favorite for international carriers.",
                maxRange: 10800,
                cruiseSpeed: 871,
                maxSeats: 440,
                fuelCapacity: 139090,
                fuelBurnRate: 5.8,
                minRunwayLength: 2770,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 264_000_000,
                maintenanceCostPerHour: 8500,
                yearIntroduced: 1993,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "A330neo-900",
                name: "Airbus A330-900neo",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The enhanced A330 with new engines and improved aerodynamics. 14% lower fuel consumption extends the A330's competitive life.",
                maxRange: 13334,
                cruiseSpeed: 871,
                maxSeats: 460,
                fuelCapacity: 139090,
                fuelBurnRate: 5.2,
                minRunwayLength: 2770,
                defaultSeating: SeatingConfig(economy: 264, premiumEconomy: 54, business: 30, first: 6),
                purchasePrice: 296_400_000,
                maintenanceCostPerHour: 8200,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 15
            ),
            Aircraft(
                modelCode: "A340-300",
                name: "Airbus A340-300",
                manufacturer: .airbus,
                category: .wideBody,
                description: "A four-engine long-haul aircraft designed for ultra-long routes. The extra engines provided ETOPS-free operations over remote areas.",
                maxRange: 13500,
                cruiseSpeed: 871,
                maxSeats: 440,
                fuelCapacity: 147850,
                fuelBurnRate: 6.5,
                minRunwayLength: 2990,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 275_000_000,
                maintenanceCostPerHour: 9200,
                yearIntroduced: 1993,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "A340-600",
                name: "Airbus A340-600",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The longest commercial airliner when introduced. Exceptional range and capacity made it ideal for prestige long-haul routes.",
                maxRange: 14630,
                cruiseSpeed: 871,
                maxSeats: 475,
                fuelCapacity: 204500,
                fuelBurnRate: 7.2,
                minRunwayLength: 3000,
                defaultSeating: SeatingConfig(economy: 280, premiumEconomy: 56, business: 30, first: 8),
                purchasePrice: 302_000_000,
                maintenanceCostPerHour: 10500,
                yearIntroduced: 2002,
                isEndgame: false,
                isSupersonic: false,
                pilots: 4,
                flightAttendents: 20
            ),
            Aircraft(
                modelCode: "A350-900",
                name: "Airbus A350-900",
                manufacturer: .airbus,
                category: .wideBody,
                description: "Airbus's cutting-edge wide-body featuring carbon-fiber construction. Advanced technology and efficiency redefine long-haul travel.",
                maxRange: 15000,
                cruiseSpeed: 903,
                maxSeats: 440,
                fuelCapacity: 138000,
                fuelBurnRate: 5.4,
                minRunwayLength: 2600,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 317_400_000,
                maintenanceCostPerHour: 8800,
                yearIntroduced: 2015,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 4,
                flightAttendents: 18
            ),
            Aircraft(
                modelCode: "A350-1000",
                name: "Airbus A350-1000",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The largest A350 variant with exceptional range and capacity. Competes directly with the 777-300ER with better efficiency.",
                maxRange: 16100,
                cruiseSpeed: 903,
                maxSeats: 480,
                fuelCapacity: 156000,
                fuelBurnRate: 5.9,
                minRunwayLength: 2750,
                defaultSeating: SeatingConfig(economy: 276, premiumEconomy: 60, business: 32, first: 8),
                purchasePrice: 366_500_000,
                maintenanceCostPerHour: 9500,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 4,
                flightAttendents: 20
            ),
            Aircraft(
                modelCode: "A380-800",
                name: "Airbus A380-800",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The world's largest passenger airliner, an engineering marvel. Double-deck luxury and massive capacity redefined ultra-long-haul travel.",
                maxRange: 15200,
                cruiseSpeed: 903,
                maxSeats: 853,
                fuelCapacity: 323546,
                fuelBurnRate: 11.5,
                minRunwayLength: 2900,
                defaultSeating: SeatingConfig(economy: 450, premiumEconomy: 96, business: 58, first: 14),
                purchasePrice: 445_600_000,
                maintenanceCostPerHour: 18000,
                yearIntroduced: 2007,
                isEndgame: true,
                isSupersonic: false,
                pilots: 4,
                flightAttendents: 36
            ),
            Aircraft(
                modelCode: "B767-300ER",
                name: "Boeing 767-300ER",
                manufacturer: .boeing,
                category: .wideBody,
                description: "A medium wide-body perfect for transatlantic routes. The 767's efficiency and versatility made it a stalwart of international fleets.",
                maxRange: 11070,
                cruiseSpeed: 851,
                maxSeats: 351,
                fuelCapacity: 91370,
                fuelBurnRate: 4.8,
                minRunwayLength: 2590,
                defaultSeating: SeatingConfig(economy: 216, premiumEconomy: 42, business: 24, first: 4),
                purchasePrice: 217_900_000,
                maintenanceCostPerHour: 7200,
                yearIntroduced: 1988,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 12
            ),
            Aircraft(
                modelCode: "B777-300ER",
                name: "Boeing 777-300ER",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The world's most successful long-haul airliner. Exceptional range, capacity, and reliability dominate ultra-long-haul routes.",
                maxRange: 13649,
                cruiseSpeed: 892,
                maxSeats: 550,
                fuelCapacity: 181280,
                fuelBurnRate: 7.8,
                minRunwayLength: 3050,
                defaultSeating: SeatingConfig(economy: 310, premiumEconomy: 66, business: 38, first: 8),
                purchasePrice: 375_500_000,
                maintenanceCostPerHour: 11500,
                yearIntroduced: 2004,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 3,
                flightAttendents: 17
            ),
            Aircraft(
                modelCode: "B777X-9",
                name: "Boeing 777-9X",
                manufacturer: .boeing,
                category: .wideBody,
                description: "Boeing's next-generation flagship with folding wingtips. Revolutionary engines and composite wings deliver unprecedented efficiency.",
                maxRange: 13500,
                cruiseSpeed: 892,
                maxSeats: 426,
                fuelCapacity: 197977,
                fuelBurnRate: 7.2,
                minRunwayLength: 3050,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 52, business: 30, first: 6),
                purchasePrice: 442_200_000,
                maintenanceCostPerHour: 12000,
                yearIntroduced: 2024,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B787-9",
                name: "Boeing 787-9 'Dreamliner'",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The Dreamliner that revolutionized long-haul travel. Composite construction and advanced systems provide 20% better fuel efficiency.",
                maxRange: 14140,
                cruiseSpeed: 903,
                maxSeats: 420,
                fuelCapacity: 126206,
                fuelBurnRate: 5.6,
                minRunwayLength: 2800,
                defaultSeating: SeatingConfig(economy: 246, premiumEconomy: 48, business: 28, first: 6),
                purchasePrice: 292_500_000,
                maintenanceCostPerHour: 8600,
                yearIntroduced: 2014,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B787-10",
                name: "Boeing 787-10 'Dreamliner'",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The largest Dreamliner variant optimized for high-capacity routes. Maintains 787 efficiency while maximizing passenger count.",
                maxRange: 11910,
                cruiseSpeed: 903,
                maxSeats: 440,
                fuelCapacity: 126206,
                fuelBurnRate: 5.8,
                minRunwayLength: 2800,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 54, business: 30, first: 6),
                purchasePrice: 325_800_000,
                maintenanceCostPerHour: 9000,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B747-100",
                name: "Boeing 747-100",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The original Queen of the Skies that democratized air travel. Its distinctive hump and massive size changed aviation forever.",
                maxRange: 9800,
                cruiseSpeed: 907,
                maxSeats: 550,
                fuelCapacity: 183380,
                fuelBurnRate: 10.5,
                minRunwayLength: 3200,
                defaultSeating: SeatingConfig(economy: 324, premiumEconomy: 66, business: 36, first: 8),
                purchasePrice: 190_000_000,
                maintenanceCostPerHour: 12000,
                yearIntroduced: 1970,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 3,
                flightAttendents: 11
            ),
            Aircraft(
                modelCode: "B747-200C",
                name: "Boeing 747-200C",
                manufacturer: .boeing,
                category: .wideBody,
                description: "An improved 747 with greater range and convertible cargo capability. The workhorse variant that proved the 747 concept worldwide.",
                maxRange: 12700,
                cruiseSpeed: 907,
                maxSeats: 500,
                fuelCapacity: 199158,
                fuelBurnRate: 10.8,
                minRunwayLength: 3190,
                defaultSeating: SeatingConfig(economy: 300, premiumEconomy: 60, business: 32, first: 6),
                purchasePrice: 210_000_000,
                maintenanceCostPerHour: 12500,
                yearIntroduced: 1971,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 15
            ),
            Aircraft(
                modelCode: "B747-400",
                name: "Boeing 747-400",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The most successful 747 variant with modern avionics and winglets. Dominated long-haul travel for two decades as the flagship of fleets.",
                maxRange: 13450,
                cruiseSpeed: 907,
                maxSeats: 660,
                fuelCapacity: 216840,
                fuelBurnRate: 11.2,
                minRunwayLength: 3090,
                defaultSeating: SeatingConfig(economy: 376, premiumEconomy: 78, business: 42, first: 10),
                purchasePrice: 266_500_000,
                maintenanceCostPerHour: 13500,
                yearIntroduced: 1989,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 21
            ),
            Aircraft(
                modelCode: "B747-8I",
                name: "Boeing 747-8i",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The final evolution of the 747, the longest passenger airliner. Advanced engines and aerodynamics keep the Queen competitive.",
                maxRange: 14815,
                cruiseSpeed: 907,
                maxSeats: 605,
                fuelCapacity: 238610,
                fuelBurnRate: 10.8,
                minRunwayLength: 3100,
                defaultSeating: SeatingConfig(economy: 346, premiumEconomy: 72, business: 40, first: 10),
                purchasePrice: 418_400_000,
                maintenanceCostPerHour: 15000,
                yearIntroduced: 2012,
                isEndgame: true,
                isSupersonic: false,
                pilots: 4,
                flightAttendents: 26
            ),
            Aircraft(
                modelCode: "DC10-30",
                name: "McDonnell Douglas DC-10-30",
                manufacturer: .mcdonnellDouglas,
                category: .wideBody,
                description: "A pioneering tri-jet wide-body for long-haul operations. The DC-10 opened new routes previously impossible for twin-engine aircraft.",
                maxRange: 10410,
                cruiseSpeed: 908,
                maxSeats: 380,
                fuelCapacity: 138710,
                fuelBurnRate: 8.2,
                minRunwayLength: 3020,
                defaultSeating: SeatingConfig(economy: 234, premiumEconomy: 48, business: 26, first: 4),
                purchasePrice: 180_000_000,
                maintenanceCostPerHour: 9500,
                yearIntroduced: 1972,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 8
            ),
            Aircraft(
                modelCode: "MD11",
                name: "McDonnell Douglas MD-11",
                manufacturer: .mcdonnellDouglas,
                category: .wideBody,
                description: "The stretched, modernized DC-10 with advanced systems. Though commercially challenged, it found success as a freighter.",
                maxRange: 12670,
                cruiseSpeed: 876,
                maxSeats: 410,
                fuelCapacity: 146200,
                fuelBurnRate: 7.9,
                minRunwayLength: 2990,
                defaultSeating: SeatingConfig(economy: 246, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 205_000_000,
                maintenanceCostPerHour: 10000,
                yearIntroduced: 1990,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "IL96-400M",
                name: "Ilyushin IL-96-400M",
                manufacturer: .ilyushin,
                category: .wideBody,
                description: "Russia's modern four-engine wide-body with Western engines. Designed for long-haul international routes with Russian reliability.",
                maxRange: 10000,
                cruiseSpeed: 870,
                maxSeats: 436,
                fuelCapacity: 175000,
                fuelBurnRate: 8.5,
                minRunwayLength: 2850,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 54, business: 28, first: 6),
                purchasePrice: 175_000_000,
                maintenanceCostPerHour: 9200,
                yearIntroduced: 2012,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 9
            )
        ]
    }
    
    // Helper functions
    func aircraft(byCode code: String) -> Aircraft? {
        allAircraft.first { $0.modelCode == code }
    }
    
    func aircraft(byCategory category: AircraftCategory) -> [Aircraft] {
        allAircraft.filter { $0.category == category }
    }
    
    func aircraft(byManufacturer manufacturer: AircraftManufacturer) -> [Aircraft] {
        allAircraft.filter { $0.manufacturer == manufacturer }
    }
    
    func endgameAircraft() -> [Aircraft] {
        allAircraft.filter { $0.isEndgame }
    }
    
    func supersonicAircraft() -> [Aircraft] {
        allAircraft.filter { $0.isSupersonic }
    }
    
    func affordableAircraft(budget: Double) -> [Aircraft] {
        allAircraft.filter { $0.purchasePrice <= budget }
    }
    
    func aircraftForRoute(distance: Int, runwayLength: Int) -> [Aircraft] {
        allAircraft.filter { aircraft in
            aircraft.maxRange >= distance && aircraft.minRunwayLength <= runwayLength
        }
    }
}

// MARK: Airport Databae

class AirportDatabase {
    static let shared = AirportDatabase()
    
    let allAirports: [Airport]
    
    private init() {
        allAirports = [
            // ASIA
            Airport(
                name: "Indira Gandhi International Airport",
                city: "Delhi",
                country: "India",
                iata: "DEL",
                icao: "VIDP",
                region: .asia,
                latitude: 28.5665,
                longitude: 77.1031,
                runwayLength: 4430,
                elevation: 237,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.1, businessTravelRatio: 0.65, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 2800, gatesAvailable: 95, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Chhatrapati Shivaji Maharaj International Airport",
                city: "Mumbai",
                country: "India",
                iata: "BOM",
                icao: "VABB",
                region: .asia,
                latitude: 19.0896,
                longitude: 72.8656,
                runwayLength: 3660,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.5, businessTravelRatio: 0.70, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3200, gatesAvailable: 85, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Kempegowda International Airport",
                city: "Bengaluru",
                country: "India",
                iata: "BLR",
                icao: "VOBL",
                region: .asia,
                latitude: 13.1979,
                longitude: 77.7063,
                runwayLength: 4000,
                elevation: 915,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.75, tourismBoost: 0.50),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2500, gatesAvailable: 70, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Chennai International Airport",
                city: "Chennai",
                country: "India",
                iata: "MAA",
                icao: "VOMM",
                region: .asia,
                latitude: 12.9941,
                longitude: 80.1709,
                runwayLength: 3660,
                elevation: 16,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.60, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 2200, gatesAvailable: 60, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Rajiv Gandhi International Airport",
                city: "Hyderabad",
                country: "India",
                iata: "HYD",
                icao: "VOHS",
                region: .asia,
                latitude: 17.2403,
                longitude: 78.4294,
                runwayLength: 4260,
                elevation: 625,
                demand: AirportDemand(passengerDemand: 8.0, cargoDemand: 7.2, businessTravelRatio: 0.68, tourismBoost: 0.55),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2400, gatesAvailable: 65, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Singapore Changi Airport",
                city: "Singapore",
                country: "Singapore",
                iata: "SIN",
                icao: "WSSS",
                region: .asia,
                latitude: 1.3644,
                longitude: 103.9915,
                runwayLength: 4000,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.5, businessTravelRatio: 0.80, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 220000, cargoCapacity: 4500, gatesAvailable: 115, slotEfficiency: 0.95)
            ),
            Airport(
                name: "Kuala Lumpur International Airport",
                city: "Kuala Lumpur",
                country: "Malaysia",
                iata: "KUL",
                icao: "WMKK",
                region: .asia,
                latitude: 2.7456,
                longitude: 101.7099,
                runwayLength: 4000,
                elevation: 21,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.65, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3000, gatesAvailable: 90, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Suvarnabhumi Airport",
                city: "Bangkok",
                country: "Thailand",
                iata: "BKK",
                icao: "VTBS",
                region: .asia,
                latitude: 13.6900,
                longitude: 100.7501,
                runwayLength: 4000,
                elevation: 2,
                demand: AirportDemand(passengerDemand: 9.3, cargoDemand: 8.3, businessTravelRatio: 0.55, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 190000, cargoCapacity: 3500, gatesAvailable: 100, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Shanghai Pudong International Airport",
                city: "Shanghai",
                country: "China",
                iata: "PVG",
                icao: "ZSPD",
                region: .asia,
                latitude: 31.1443,
                longitude: 121.8083,
                runwayLength: 4000,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.7, cargoDemand: 9.8, businessTravelRatio: 0.72, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 5000, gatesAvailable: 110, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Incheon International Airport",
                city: "Seoul",
                country: "South Korea",
                iata: "ICN",
                icao: "RKSI",
                region: .asia,
                latitude: 37.4602,
                longitude: 126.4407,
                runwayLength: 3750,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 9.2, businessTravelRatio: 0.75, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 195000, cargoCapacity: 4200, gatesAvailable: 105, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Narita International Airport",
                city: "Tokyo",
                country: "Japan",
                iata: "NRT",
                icao: "RJAA",
                region: .asia,
                latitude: 35.7647,
                longitude: 140.3864,
                runwayLength: 4000,
                elevation: 43,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 9.0, businessTravelRatio: 0.70, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 4000, gatesAvailable: 95, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Tokyo Haneda Airport",
                city: "Tokyo",
                country: "Japan",
                iata: "HND",
                icao: "RJTT",
                region: .asia,
                latitude: 35.5494,
                longitude: 139.7798,
                runwayLength: 3000,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 7.5, businessTravelRatio: 0.82, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 210000, cargoCapacity: 2800, gatesAvailable: 100, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Dubai International Airport",
                city: "Dubai",
                country: "United Arab Emirates",
                iata: "DXB",
                icao: "OMDB",
                region: .asia,
                latitude: 25.2532,
                longitude: 55.3657,
                runwayLength: 4000,
                elevation: 19,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.0, businessTravelRatio: 0.78, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 230000, cargoCapacity: 4800, gatesAvailable: 120, slotEfficiency: 0.94)
            ),
            Airport(
                name: "Hamad International Airport",
                city: "Doha",
                country: "Qatar",
                iata: "DOH",
                icao: "OTHH",
                region: .asia,
                latitude: 25.2731,
                longitude: 51.6080,
                runwayLength: 4850,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.7, businessTravelRatio: 0.76, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3800, gatesAvailable: 95, slotEfficiency: 0.92)
            ),
            Airport(
                name: "King Khalid International Airport",
                city: "Riyadh",
                country: "Saudi Arabia",
                iata: "RUH",
                icao: "OERK",
                region: .asia,
                latitude: 24.9576,
                longitude: 46.6988,
                runwayLength: 4205,
                elevation: 612,
                demand: AirportDemand(passengerDemand: 8.3, cargoDemand: 7.5, businessTravelRatio: 0.72, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2900, gatesAvailable: 80, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Muscat International Airport",
                city: "Muscat",
                country: "Oman",
                iata: "MCT",
                icao: "OOMS",
                region: .asia,
                latitude: 23.5933,
                longitude: 58.2844,
                runwayLength: 4000,
                elevation: 15,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 6.5, businessTravelRatio: 0.60, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 55, slotEfficiency: 0.83)
            ),
            
            // EUROPE
            Airport(
                name: "Vienna International Airport",
                city: "Vienna",
                country: "Austria",
                iata: "VIE",
                icao: "LOWW",
                region: .europe,
                latitude: 48.1103,
                longitude: 16.5697,
                runwayLength: 3500,
                elevation: 183,
                demand: AirportDemand(passengerDemand: 8.0, cargoDemand: 7.2, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2600, gatesAvailable: 70, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Riga International Airport",
                city: "Riga",
                country: "Latvia",
                iata: "RIX",
                icao: "EVRA",
                region: .europe,
                latitude: 56.9236,
                longitude: 23.9711,
                runwayLength: 3200,
                elevation: 10,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 5.8, businessTravelRatio: 0.55, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 1800, gatesAvailable: 45, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Leonardo da Vinci-Fiumicino Airport",
                city: "Rome",
                country: "Italy",
                iata: "FCO",
                icao: "LIRF",
                region: .europe,
                latitude: 41.8003,
                longitude: 12.2389,
                runwayLength: 3900,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 7.5, businessTravelRatio: 0.62, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 2800, gatesAvailable: 85, slotEfficiency: 0.87)
            ),
            Airport(
                name: "London Heathrow Airport",
                city: "London",
                country: "United Kingdom",
                iata: "LHR",
                icao: "EGLL",
                region: .europe,
                latitude: 51.4700,
                longitude: -0.4543,
                runwayLength: 3902,
                elevation: 25,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 8.8, businessTravelRatio: 0.80, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 225000, cargoCapacity: 3800, gatesAvailable: 115, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Adolfo Suárez Madrid-Barajas Airport",
                city: "Madrid",
                country: "Spain",
                iata: "MAD",
                icao: "LEMD",
                region: .europe,
                latitude: 40.4719,
                longitude: -3.5626,
                runwayLength: 4179,
                elevation: 610,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 7.8, businessTravelRatio: 0.65, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 3000, gatesAvailable: 90, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Charles de Gaulle Airport",
                city: "Paris",
                country: "France",
                iata: "CDG",
                icao: "LFPG",
                region: .europe,
                latitude: 49.0097,
                longitude: 2.5479,
                runwayLength: 4200,
                elevation: 119,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.0, businessTravelRatio: 0.75, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 210000, cargoCapacity: 4200, gatesAvailable: 110, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Frankfurt Airport",
                city: "Frankfurt",
                country: "Germany",
                iata: "FRA",
                icao: "EDDF",
                region: .europe,
                latitude: 50.0379,
                longitude: 8.5622,
                runwayLength: 4000,
                elevation: 111,
                demand: AirportDemand(passengerDemand: 9.7, cargoDemand: 9.5, businessTravelRatio: 0.82, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 205000, cargoCapacity: 5000, gatesAvailable: 108, slotEfficiency: 0.94)
            ),
            Airport(
                name: "Munich Airport",
                city: "Munich",
                country: "Germany",
                iata: "MUC",
                icao: "EDDM",
                region: .europe,
                latitude: 48.3537,
                longitude: 11.7750,
                runwayLength: 4000,
                elevation: 453,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.2, businessTravelRatio: 0.75, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3500, gatesAvailable: 95, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Václav Havel Airport Prague",
                city: "Prague",
                country: "Czech Republic",
                iata: "PRG",
                icao: "LKPR",
                region: .europe,
                latitude: 50.1008,
                longitude: 14.2600,
                runwayLength: 3715,
                elevation: 380,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2200, gatesAvailable: 65, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Francisco Sá Carneiro Airport",
                city: "Porto",
                country: "Portugal",
                iata: "OPO",
                icao: "LPPR",
                region: .europe,
                latitude: 41.2481,
                longitude: -8.6814,
                runwayLength: 3480,
                elevation: 69,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 6.0, businessTravelRatio: 0.52, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 1900, gatesAvailable: 55, slotEfficiency: 0.84)
            ),
            Airport(
                name: "Zagreb Airport",
                city: "Zagreb",
                country: "Croatia",
                iata: "ZAG",
                icao: "LDZA",
                region: .europe,
                latitude: 45.7429,
                longitude: 16.0688,
                runwayLength: 3252,
                elevation: 108,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.5, businessTravelRatio: 0.50, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1600, gatesAvailable: 40, slotEfficiency: 0.81)
            ),
            Airport(
                name: "Budapest Ferenc Liszt International Airport",
                city: "Budapest",
                country: "Hungary",
                iata: "BUD",
                icao: "LHBP",
                region: .europe,
                latitude: 47.4298,
                longitude: 19.2611,
                runwayLength: 3707,
                elevation: 151,
                demand: AirportDemand(passengerDemand: 7.3, cargoDemand: 6.8, businessTravelRatio: 0.60, tourismBoost: 0.83),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2100, gatesAvailable: 60, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Warsaw Chopin Airport",
                city: "Warsaw",
                country: "Poland",
                iata: "WAW",
                icao: "EPWA",
                region: .europe,
                latitude: 52.1657,
                longitude: 20.9671,
                runwayLength: 3690,
                elevation: 110,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.65, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2400, gatesAvailable: 70, slotEfficiency: 0.87)
            ),
            
            // AFRICA
            Airport(
                name: "Félix-Houphouët-Boigny International Airport",
                city: "Abidjan",
                country: "Ivory Coast",
                iata: "ABJ",
                icao: "DIAP",
                region: .africa,
                latitude: 5.2539,
                longitude: -3.9263,
                runwayLength: 3000,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 6.0, cargoDemand: 5.5, businessTravelRatio: 0.55, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1700, gatesAvailable: 35, slotEfficiency: 0.75)
            ),
            Airport(
                name: "Cape Town International Airport",
                city: "Cape Town",
                country: "South Africa",
                iata: "CPT",
                icao: "FACT",
                region: .africa,
                latitude: -33.9648,
                longitude: 18.6017,
                runwayLength: 3201,
                elevation: 46,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 6.8, businessTravelRatio: 0.58, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 2300, gatesAvailable: 65, slotEfficiency: 0.84)
            ),
            Airport(
                name: "N'djili International Airport",
                city: "Kinshasa",
                country: "Democratic Republic of Congo",
                               iata: "FIH",
                icao: "FZAA",
                region: .africa,
                latitude: -4.3857,
                longitude: 15.4446,
                runwayLength: 4700,
                elevation: 309,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.48, tourismBoost: 0.45),
                facilities: AirportFacilities(terminalCapacity: 70000, cargoCapacity: 1500, gatesAvailable: 30, slotEfficiency: 0.72)
            ),
            Airport(
                name: "Julius Nyerere International Airport",
                city: "Dar es Salaam",
                country: "Tanzania",
                iata: "DAR",
                icao: "HTDA",
                region: .africa,
                latitude: -6.8781,
                longitude: 39.2026,
                runwayLength: 3000,
                elevation: 17,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 6.0, businessTravelRatio: 0.52, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 1900, gatesAvailable: 42, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Jomo Kenyatta International Airport",
                city: "Nairobi",
                country: "Kenya",
                iata: "NBO",
                icao: "HKJK",
                region: .africa,
                latitude: -1.3192,
                longitude: 36.9278,
                runwayLength: 4117,
                elevation: 1625,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.2, businessTravelRatio: 0.62, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2500, gatesAvailable: 58, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Murtala Muhammed International Airport",
                city: "Lagos",
                country: "Nigeria",
                iata: "LOS",
                icao: "DNMM",
                region: .africa,
                latitude: 6.5774,
                longitude: 3.3212,
                runwayLength: 3900,
                elevation: 42,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.65, tourismBoost: 0.58),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2300, gatesAvailable: 60, slotEfficiency: 0.79)
            ),
            Airport(
                name: "Houari Boumediene Airport",
                city: "Algiers",
                country: "Algeria",
                iata: "ALG",
                icao: "DAAG",
                region: .africa,
                latitude: 36.6910,
                longitude: 3.2154,
                runwayLength: 3500,
                elevation: 25,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.2, businessTravelRatio: 0.58, tourismBoost: 0.68),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 50, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Marrakesh Menara Airport",
                city: "Marrakesh",
                country: "Morocco",
                iata: "RAK",
                icao: "GMMX",
                region: .africa,
                latitude: 31.6069,
                longitude: -8.0363,
                runwayLength: 3100,
                elevation: 466,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 5.5, businessTravelRatio: 0.42, tourismBoost: 0.95),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 1600, gatesAvailable: 48, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Cairo International Airport",
                city: "Cairo",
                country: "Egypt",
                iata: "CAI",
                icao: "HECA",
                region: .africa,
                latitude: 30.1219,
                longitude: 31.4056,
                runwayLength: 4000,
                elevation: 116,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.5, businessTravelRatio: 0.60, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 155000, cargoCapacity: 2700, gatesAvailable: 75, slotEfficiency: 0.85)
            ),
            
            // NORTH AMERICA
            Airport(
                name: "Los Angeles International Airport",
                city: "Los Angeles",
                country: "United States",
                iata: "LAX",
                icao: "KLAX",
                region: .northAmerica,
                latitude: 33.9416,
                longitude: -118.4085,
                runwayLength: 3939,
                elevation: 38,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.0, businessTravelRatio: 0.72, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 240000, cargoCapacity: 4500, gatesAvailable: 130, slotEfficiency: 0.92)
            ),
            Airport(
                name: "San Francisco International Airport",
                city: "San Francisco",
                country: "United States",
                iata: "SFO",
                icao: "KSFO",
                region: .northAmerica,
                latitude: 37.6213,
                longitude: -122.3790,
                runwayLength: 3618,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 8.5, businessTravelRatio: 0.78, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 4000, gatesAvailable: 115, slotEfficiency: 0.91)
            ),
            Airport(
                name: "John F. Kennedy International Airport",
                city: "New York",
                country: "United States",
                iata: "JFK",
                icao: "KJFK",
                region: .northAmerica,
                latitude: 40.6413,
                longitude: -73.7781,
                runwayLength: 4423,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.5, businessTravelRatio: 0.82, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 250000, cargoCapacity: 5200, gatesAvailable: 128, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Newark Liberty International Airport",
                city: "Newark",
                country: "United States",
                iata: "EWR",
                icao: "KEWR",
                region: .northAmerica,
                latitude: 40.6895,
                longitude: -74.1745,
                runwayLength: 3353,
                elevation: 5,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.8, businessTravelRatio: 0.80, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 185000, cargoCapacity: 3800, gatesAvailable: 102, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Tampa International Airport",
                city: "Tampa",
                country: "United States",
                iata: "TPA",
                icao: "KTPA",
                region: .northAmerica,
                latitude: 27.9755,
                longitude: -82.5332,
                runwayLength: 3353,
                elevation: 8,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 2200, gatesAvailable: 68, slotEfficiency: 0.87)
            ),
            Airport(
                name: "O'Hare International Airport",
                city: "Chicago",
                country: "United States",
                iata: "ORD",
                icao: "KORD",
                region: .northAmerica,
                latitude: 41.9742,
                longitude: -87.9073,
                runwayLength: 3962,
                elevation: 205,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.2, businessTravelRatio: 0.78, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 230000, cargoCapacity: 4800, gatesAvailable: 185, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Ottawa Macdonald-Cartier International Airport",
                city: "Ottawa",
                country: "Canada",
                iata: "YOW",
                icao: "CYOW",
                region: .northAmerica,
                latitude: 45.3225,
                longitude: -75.6692,
                runwayLength: 3048,
                elevation: 114,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.0, businessTravelRatio: 0.68, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 52, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Toronto Pearson International Airport",
                city: "Toronto",
                country: "Canada",
                iata: "YYZ",
                icao: "CYYZ",
                region: .northAmerica,
                latitude: 43.6777,
                longitude: -79.6248,
                runwayLength: 3389,
                elevation: 173,
                demand: AirportDemand(passengerDemand: 9.3, cargoDemand: 8.5, businessTravelRatio: 0.75, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 195000, cargoCapacity: 3800, gatesAvailable: 105, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Calgary International Airport",
                city: "Calgary",
                country: "Canada",
                iata: "YYC",
                icao: "CYYC",
                region: .northAmerica,
                latitude: 51.1139,
                longitude: -114.0203,
                runwayLength: 3658,
                elevation: 1076,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.0, businessTravelRatio: 0.70, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2600, gatesAvailable: 65, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Harry Reid International Airport",
                city: "Las Vegas",
                country: "United States",
                iata: "LAS",
                icao: "KLAS",
                region: .northAmerica,
                latitude: 36.0840,
                longitude: -115.1537,
                runwayLength: 4423,
                elevation: 664,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 7.2, businessTravelRatio: 0.52, tourismBoost: 0.98),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 2800, gatesAvailable: 95, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Monterey Regional Airport",
                city: "Monterey",
                country: "United States",
                iata: "MRY",
                icao: "KMRY",
                region: .northAmerica,
                latitude: 36.5870,
                longitude: -121.8430,
                runwayLength: 2348,
                elevation: 78,
                demand: AirportDemand(passengerDemand: 4.5, cargoDemand: 3.5, businessTravelRatio: 0.45, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 50000, cargoCapacity: 800, gatesAvailable: 18, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Mexico City International Airport",
                city: "Mexico City",
                country: "Mexico",
                iata: "MEX",
                icao: "MMMX",
                region: .northAmerica,
                latitude: 19.4363,
                longitude: -99.0721,
                runwayLength: 3900,
                elevation: 2230,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.0, businessTravelRatio: 0.68, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3500, gatesAvailable: 85, slotEfficiency: 0.86)
            ),
            Airport(
                name: "José Martí International Airport",
                city: "Havana",
                country: "Cuba",
                iata: "HAV",
                icao: "MUHA",
                region: .northAmerica,
                latitude: 22.9892,
                longitude: -82.4091,
                runwayLength: 4000,
                elevation: 64,
                demand: AirportDemand(passengerDemand: 6.0, cargoDemand: 4.5, businessTravelRatio: 0.38, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 1400, gatesAvailable: 38, slotEfficiency: 0.75)
            ),
            
            // SOUTH AMERICA
            Airport(
                name: "Tocumen International Airport",
                city: "Panama City",
                country: "Panama",
                iata: "PTY",
                icao: "MPTO",
                region: .southAmerica,
                latitude: 9.0714,
                longitude: -79.3835,
                runwayLength: 3050,
                elevation: 27,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.5, businessTravelRatio: 0.62, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2800, gatesAvailable: 68, slotEfficiency: 0.86)
            ),
            Airport(
                name: "El Dorado International Airport",
                city: "Bogotá",
                country: "Colombia",
                iata: "BOG",
                icao: "SKBO",
                region: .southAmerica,
                latitude: 4.7016,
                longitude: -74.1469,
                runwayLength: 3800,
                elevation: 2548,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 7.8, businessTravelRatio: 0.65, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3200, gatesAvailable: 75, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Simón Bolívar International Airport",
                city: "Caracas",
                country: "Venezuela",
                iata: "CCS",
                icao: "SVMI",
                region: .southAmerica,
                latitude: 10.6013,
                longitude: -66.9905,
                runwayLength: 3500,
                elevation: 72,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.52, tourismBoost: 0.58),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1600, gatesAvailable: 40, slotEfficiency: 0.72)
            ),
            Airport(
                name: "Jorge Chávez International Airport",
                city: "Lima",
                country: "Peru",
                iata: "LIM",
                icao: "SPJC",
                region: .southAmerica,
                latitude: -12.0219,
                longitude: -77.1143,
                runwayLength: 3507,
                elevation: 34,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.2, businessTravelRatio: 0.60, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2700, gatesAvailable: 70, slotEfficiency: 0.85)
            ),
            Airport(
                name: "El Alto International Airport",
                city: "La Paz",
                country: "Bolivia",
                iata: "LPB",
                icao: "SLLP",
                region: .southAmerica,
                latitude: -16.5133,
                longitude: -68.1923,
                runwayLength: 4000,
                elevation: 4061,
                demand: AirportDemand(passengerDemand: 5.8, cargoDemand: 5.2, businessTravelRatio: 0.55, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1700, gatesAvailable: 38, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Arturo Merino Benítez International Airport",
                city: "Santiago",
                country: "Chile",
                iata: "SCL",
                icao: "SCEL",
                region: .southAmerica,
                latitude: -33.3930,
                longitude: -70.7858,
                runwayLength: 3800,
                elevation: 474,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 3000, gatesAvailable: 80, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Ministro Pistarini International Airport",
                city: "Buenos Aires",
                country: "Argentina",
                iata: "EZE",
                icao: "SAEZ",
                region: .southAmerica,
                latitude: -34.8222,
                longitude: -58.5358,
                runwayLength: 3300,
                elevation: 20,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.70, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3300, gatesAvailable: 85, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Brasília International Airport",
                city: "Brasília",
                country: "Brazil",
                iata: "BSB",
                icao: "SBBR",
                region: .southAmerica,
                latitude: -15.8697,
                longitude: -47.9208,
                runwayLength: 3200,
                elevation: 1061,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.0, businessTravelRatio: 0.72, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2500, gatesAvailable: 65, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Rio de Janeiro-Galeão International Airport",
                city: "Rio de Janeiro",
                country: "Brazil",
                iata: "GIG",
                icao: "SBGL",
                region: .southAmerica,
                latitude: -22.8099,
                longitude: -43.2505,
                runwayLength: 4000,
                elevation: 9,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.5, businessTravelRatio: 0.60, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 2900, gatesAvailable: 78, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Carrasco International Airport",
                city: "Montevideo",
                country: "Uruguay",
                iata: "MVD",
                icao: "SUMU",
                region: .southAmerica,
                latitude: -34.8384,
                longitude: -56.0308,
                runwayLength: 2720,
                elevation: 34,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.5, businessTravelRatio: 0.58, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 1800, gatesAvailable: 42, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Silvio Pettirossi International Airport",
                city: "Asunción",
                country: "Paraguay",
                iata: "ASU",
                icao: "SGAS",
                region: .southAmerica,
                latitude: -25.2395,
                longitude: -57.5196,
                runwayLength: 3353,
                elevation: 94,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.55, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1600, gatesAvailable: 35, slotEfficiency: 0.79)
            )
        ]
    }
    
    // Helper functions
    func airport(byCode code: String) -> Airport? {
        allAirports.first { $0.iata == code || $0.icao == code }
    }
    
    func airports(byRegion region: Region) -> [Airport] {
        allAirports.filter { $0.region == region }
    }
    
    func airports(byCountry country: String) -> [Airport] {
        allAirports.filter { $0.country == country }
    }
    
    func majorHubs() -> [Airport] {
        allAirports.filter { $0.demand.passengerDemand >= 9.0 }
    }
    
    func calculateDistance(from: Airport, to: Airport) -> Int {
        // Haversine formula for great circle distance
        let earthRadius = 6371.0 // km
        let lat1 = from.latitude * .pi / 180
        let lat2 = to.latitude * .pi / 180
        let dLat = (to.latitude - from.latitude) * .pi / 180
        let dLon = (to.longitude - from.longitude) * .pi / 180
        
        let a = sin(dLat/2) * sin(dLat/2) +
                cos(lat1) * cos(lat2) *
                sin(dLon/2) * sin(dLon/2)
        let c = 2 * atan2(sqrt(a), sqrt(1-a))
        
        return Int(earthRadius * c)
    }
}
